version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    DSSGLOBLIST: "dss-minio-bin-*.tgz"

phases:
  pre_build:
    commands:
      - |
        sonar-scanner \
          -Dsonar.branch.name="$([[ "$GITHUB_REF_NAME" != *"/merge" ]] && echo "$GITHUB_REF_NAME")" \
          -Dsonar.pullrequest.key=$(echo $GITHUB_REF | grep -oP "^refs/pull/\K[^/]+") \
          -Dsonar.pullrequest.base=${GITHUB_BASE_REF} \
          -Dsonar.pullrequest.branch=${GITHUB_HEAD_REF} \
      - ./getminiodeps.sh
  build:
    commands:
      - ./build.sh
  post_build:
    commands:
      - /stagemergeartifacts.sh

artifacts:
  files:
    - dss-minio-bin-*.tgz
  discard-paths: yes
  name: builds/dss-minio/$CODEBUILD_BUILD_NUMBER
