name: dss-minio
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  dss-minio:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: dss-minio
      project-name: OpenMPDK_dss-minio
    secrets: inherit
